server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:brasilprev
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true

jwt:
  secret: brasilprev
  expiration: 1000000000